~clave~ is another modal editing (minor) mode for Emacs. ~clave~ pronounced as ˈklä-(ˌ)vā (from Spanish, /keystone/, /clef/, from Latin clavis, /key/).

This package is meant to demonstrate a more general practice of binding computer commands to physical keys.

* Workflow for keybindings

- in your emacs config (e.g., init.el) find where the command is defined or binded (if already binded). Here quick search would be handy.
- add dummy binding here with its description (type)
- set it to some empty keymap and key right away
- visualize current keybindings for relevant keymaps
- think where to bind it or which what to rebind it
- bind command to a key
- git commit your config with some rationale for key binding (e.g. ergonomics reasons) with special prefix in the commit message (e.g., keybindig: your command, etc.)

* Where to define keybindings in your config

- if it is my custom command and it is meant to be used in certain modes then load it in :config of this mode use-package definition and bind it there
- if it is my custom command and it can be used independently or module for other package the make it a package and define keybindings there
- bindings to emacs commands could be made in clave :config
- if bind command works only in certain mode then remap it to this mode keymap only


* Which keymaps to bind commands

- if command called repeatedly then bind it to command mode keymap(s) (e.g., cursor movements)
- if command used frequently bind it to leader map (use keyboard layout heatmap visualization of commands frequencies)
- the rest goes into leader prefix keymaps

* Leader keymaps
One hand key combos for one hand are easier when it is inward movement (e.g. from pinky to index fingers). If leader key is on Caps Lock then the following 6 prefix keymaps could be considered after pressing the Caps Lock (lead key).

Left hand:
d f g (f and g for more frequent)

Right hand
; l k (l and k easier)

* Categories for commands
For each keybinding (command) can have category.

Examples:

- Apps
  - gnus
  - emms
  - firefox
  - emacs
  - calendar
  - magit-status
  - calc
  - IDE (R)
  - vterm
- evaluations and executions
- inserts
  - expands
  - general inserts like pair of brackets
  - setting org-mode properties
- navigation
  - buffers
  - files
  - dirs
  - bookmarks
  - revisions
  - windows
- cursor movements

